In [1]:
import pandas as pd
orders=pd.read_csv('/content/Day9_Orders.csv')
customers=pd.read_csv('/content/Day9_Customers.csv')
products=pd.read_csv('/content/Day9_Products.csv')

**Using concat() to demonstrate combining DataFrames**

In [18]:
d=pd.concat([orders,customers,products],axis=1)
d

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_ID,Customer_Name,City,Region,Membership_Type,Product_ID,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,C001,Aarav Sharma,Srinagar,North,Premium,P001,Wireless Headphones,Electronics,1499.0,SoundMax
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,C002,Zoya Khan,Delhi,North,Regular,P002,Mechanical Keyboard,Electronics,2499.0,KeyPro
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,C003,Rohan Mehta,Mumbai,West,Premium,P003,Wireless Mouse,Electronics,899.0,TechGear
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,C004,Ananya Singh,Jammu,North,Regular,P004,Smart Watch,Electronics,3299.0,FitTech
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,C005,Kabir Ali,Lucknow,North,New,P005,Power Bank,Electronics,1199.0,VoltPlus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Merging the files together**

In [19]:
df=pd.merge(orders,customers,on="Customer_ID")
df

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular

In [20]:
df=df.merge(products,on="Product_ID")
df

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered,Reyansh Jain,Kolkata,East,New,Electric Kettle,Home & Kitchen,1499,KitchenPro
116,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped,Yusuf Dar,Srinagar,North,New,Machine Learning Basics,Books,999,AIPress
117,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Atomic Habits,Books,599,MindReads
118,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered,Karan Joshi,Chandigarh,North,Regular,Cricket Bat,Sports,2499,BatPro
119,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled,Rahul Das,Kolkata,East,Regular,Dumbbell Set,Sports,1999,StrongFit

**Using apply() to create Order_Value**

In [21]:
df["Order_Value"] = df.apply(lambda row: row["Quantity"] * row["Unit_Price"],axis=1)
df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,Membership_Type,Product_Name,Category,Unit_Price,Brand,Order_Value
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,Premium,Cricket Bat,Sports,2499,BatPro,4998
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,Premium,Wireless Mouse,Electronics,899,TechGear,1798
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,Regular,Smart Watch,Electronics,3299,FitTech,3299
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,Regular,Machine Learning Basics,Books,999,AIPress,2997
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,New,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495

**Using DateTime operations to convert the order date and extract information such as the month, day, or day of the week**

In [23]:
df["Order_Date"].dtype

dtype('O')

In [26]:
df["Order_Date"]=pd.to_datetime(df["Order_Date"])
df["Order_Date"].dtype

dtype('<M8[ns]')

In [29]:
df["Order_Year"]=df["Order_Date"].dt.year
df["Order_Month"]=df["Order_Date"].dt.month
df["Order_Month_Name"]=df["Order_Date"].dt.month_name()
df["Order_Day"] =df["Order_Date"].dt.day
df["Order_Day_Name"] =df["Order_Date"].dt.day_name()
df.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status,Customer_Name,City,Region,...,Product_Name,Category,Unit_Price,Brand,Order_Value,Order_Year,Order_Month,Order_Month_Name,Order_Day,Order_Day_Name
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered,Harsh Vardhan,Noida,North,...,Cricket Bat,Sports,2499,BatPro,4998,2026,2,February,19,Thursday
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered,Ishita Gupta,Bengaluru,South,...,Wireless Mouse,Electronics,899,TechGear,1798,2026,1,January,25,Sunday
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered,Karan Joshi,Chandigarh,North,...,Smart Watch,Electronics,3299,FitTech,3299,2026,2,February,26,Thursday
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered,Maryam Khan,Hyderabad,South,...,Machine Learning Basics,Books,999,AIPress,2997,2026,3,March,4,Wednesday
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered,Reyansh Jain,Kolkata,East,...,Coffee Maker,Home & Kitchen,3499,HomeBrew,17495,2026,3,March,29,Sunday

**Export to CSV**

In [30]:
df.to_csv("Processed_Ecommerce_Dataset.csv",index=False)